version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/**'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'

  - package-ecosystem: 'pip'
    directories:
      - '/**'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    pull-request-branch-name:
      separator: '-'
